# Generated by Django 4.0.2 on 2022-03-13 18:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer', models.EmailField(max_length=254)),
                ('tickets', models.IntegerField(default=1)),
                ('total_amount_to_pay', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Booked', 'BOOKED'), ('Cancel', 'CANCELLED')], default='Booked', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='buses',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=30)),
                ('plate_number', models.CharField(max_length=7)),
                ('numberofseats', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(default=12345, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_names', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_names', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_point', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departing_time', models.TimeField()),
                ('estimated_arrival_time', models.TimeField()),
                ('schedule_date', models.DateField()),
                ('price', models.CharField(max_length=200)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.buses')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.drivers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='payements',
            fields=[
                ('payement_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount_paid', models.IntegerField()),
                ('payement_date', models.DateTimeField()),
                ('payement_type', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.bookings')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.schedules'),
        ),
    ]
