# Generated by Django 4.0 on 2022-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
