# Generated by Django 4.0 on 2022-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_schedules_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_time',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('B', 'BOOKED'), ('C', 'CANCELLED')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
