# Generated by Django 4.0.2 on 2022-03-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_remove_schedules_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='customer',
            new_name='customer_email',
        ),
    ]
