# Generated by Django 4.0.2 on 2022-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_rename_customer_bookings_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='availableseats',
            field=models.IntegerField(default=0),
        ),
    ]
