# Generated by Django 4.0 on 2022-01-31 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_alter_bookings_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payements',
            name='payement_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
