# Generated by Django 4.0.2 on 2022-04-06 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_schedules_availableseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
