# Generated by Django 4.0 on 2022-01-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_alter_payements_payement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_date',
        ),
    ]
