# Generated by Django 4.0.2 on 2022-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_alter_schedules_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='From',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='To',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
