# Generated by Django 4.0 on 2022-02-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_remove_bookings_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_time',
        ),
    ]
