# Generated by Django 4.0.2 on 2022-04-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_alter_bookings_from_alter_bookings_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='username',
        ),
    ]
