# Generated by Django 4.0.2 on 2022-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_alter_customers_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_names',
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
