# Generated by Django 4.0.2 on 2022-04-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_remove_users_full_names_users_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
