# Generated by Django 4.0.2 on 2022-04-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0012_alter_bookings_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.schedules'),
        ),
    ]
