# Generated by Django 4.0.2 on 2022-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0013_alter_bookings_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='travelDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='travelTime',
            field=models.TimeField(null=True),
        ),
    ]
