# Generated by Django 4.0.2 on 2022-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0014_bookings_traveldate_bookings_traveltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bookingTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
