# Generated by Django 4.0.2 on 2022-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0015_bookings_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='ticket_code',
            field=models.CharField(default='50b73d', max_length=6),
        ),
    ]
