# Generated by Django 4.0.2 on 2022-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0016_bookings_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Bus',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='ticket_code',
            field=models.CharField(default='9990fd', max_length=6),
        ),
    ]
