# Generated by Django 4.0.2 on 2022-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0017_bookings_bus_alter_bookings_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='ticket_code',
            field=models.CharField(default='cea06b', max_length=6),
        ),
    ]
